### ISSUE TITLE
WP-Config.php Enhancement

### ISSUE THREAD

**Issue by jasoncomes** [evolution/wordpress#153]
Update `WP_POST_REVISIONS` to **3** instead of **5**  and add `define('AUTOSAVE_INTERVAL', 300);` to the _wp_config.php_

```
define('AUTOSAVE_INTERVAL', 300);
define('WP_POST_REVISIONS', 3);
```

**Comment by EvanK** [comment]
If the only customizations needed are for constants, it'd be better to define them as a dict in the group_vars file, like:

```yml
wordpress_config_consts:
  AUTOSAVE_INTERVAL: 300
  WP_POST_REVISIONS: 3
```

And then we can just render them into the wp-config upon (re)generation
